name: Schedule Probe

on:
  schedule:
    - cron: "3/5 * * * *"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "EVENT: ${{ github.event_name }}"
          date -u
